language: sh

before_script:
  - sudo add-apt-repository -y "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse"
  - sudo apt-get -y update
  - sudo apt-get -y install shellcheck

script:
  - shellcheck mac

notifications:
  email: false

branches:
  only:
    - master
